# DHCP and DNS for GoodWifi clients.
port=53
interface=wlan0
bind-dynamic
dhcp-authoritative
dhcp-range=10.42.0.10,10.42.0.100,255.255.255.0,24h
dhcp-option=3,10.42.0.1
dhcp-option=6,8.8.8.8,8.8.4.4
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
cache-size=1000
log-dhcp
ipset=/.github.com/.githubusercontent.com/.actions.githubusercontent.com/vpn_domains
