interface=wlan0
driver=nl80211
ssid=GoodWifi
country_code=US
ieee80211d=1
hw_mode=g
channel=1
beacon_int=100
dtim_period=2
wmm_enabled=1
ieee80211n=1
require_ht=0
ht_capab=[HT20][SHORT-GI-20]
ap_isolate=0
disassoc_low_ack=0
ctrl_interface=/run/hostapd
ctrl_interface_group=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=GoodPassword
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
max_num_sta=10
ap_max_inactivity=300
