ayabank.com/local_routes
ayainnovation.com/local_routes
ayapay.com/local_routes
ayapay.com.mm/local_routes
binance.com/local_routes
binance.info/local_routes
binance.me/local_routes
binance.org/local_routes
bitverse.zone/local_routes
bnbstatic.com/local_routes
bntrace.com/local_routes
byabcde.com/local_routes
byapps.net/local_routes
bybdc6.com/local_routes
bybit-aws.com/local_routes
bybit.biz/local_routes
bybit.cloud/local_routes
bybit.com/local_routes
bybit-global.com/local_routes
bybitglobal.com/local_routes
bybit.net/local_routes
bybit.org/local_routes
bycsi.com/local_routes
byd3c3.com/local_routes
by-financial.com/local_routes
bytick.com/local_routes
cbbank.com.mm/local_routes
cbbank.net/local_routes
cbpay.com.mm/local_routes
googlevideo.com/local_routes
kbzbank.com/local_routes
kbzmoney.com/local_routes
kbzpayapi.com/local_routes
kbzpay.com/local_routes
uab.com.mm/local_routes
uabpaybusiness.com/local_routes
uabpay.com.mm/local_routes
uabpayupi.com/local_routes
wavemoney.com.mm/local_routes
wavemoney.io/local_routes
wavepay.com.mm/local_routes
wavepay.io/local_routes
yomabank.com/local_routes
yoma.com.mm/local_routes
yomanext.com/local_routes
youtu.be/local_routes
youtube.com/local_routes
youtubei.googleapis.com/local_routes
youtubekids.com/local_routes
youtube-nocookie.com/local_routes
yt3.ggpht.com/local_routes
yt.be/local_routes
ytimg.com/local_routes
actions.githubusercontent.com/vpn_domains
archive.debian.org/vpn_domains
deb.debian.org/vpn_domains
github.com/vpn_domains
github.githubassets.com/vpn_domains
githubusercontent.com/vpn_domains
security.debian.org/vpn_domains
